version: '3'

services:

  database:
    image: postgres
    container_name: transcendence_database
    expose:
      - 5432
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: my-secret-pw
      POSTGRES_DB: transcendence

  # database:
  #  image: mariadb:latest
  #  container_name: transcendence_database
  #  expose:
  #    - 3306
  #  environment:
  #    MARIADB_ROOT_PASSWORD: my-secret-pw
  #    MYSQL_DATABASE: transcendence

  back:
    build: ./back
    container_name: transcendence_back
    ports:
      - 3000:3000
    volumes:
      - ./data:/data
    links:
      - database:transcendence-database

  front:
    build: ./front
    container_name: transcendence_front
    ports:
      - 8000:8000
    links:
      - back:transcendence-back

  reverse-proxy:
    image: nginx
    container_name: transcendence_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    links:
      - front:transcendence-front
      - back:transcendence-back
